apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"   
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nginx-webapp-vs
  namespace: default
spec:
  hosts:      
    - "*"
  gateways:
    - ingress-gateway-configuration
  http:
  - name: primary
    route:
    - destination:
        host: nginx-rollout-stable
      weight: 100
    - destination:
        host: nginx-rollout-canary
      weight: 0